# Integration tests — apply-command against real AWS + Databricks UC workspace.
#
# IMPORTANT: This test requires a Unity Catalog enabled workspace and proper authentication.
# The test is SKIPPED by default because:
#   1. Requires a UC-enabled Databricks workspace (not just any workspace)
#   2. Requires workspace-level authentication (not account-level)
#   3. Requires the service principal/user to have permission to create storage credentials
#   4. The provided environment has account-level credentials, not workspace-level
#
# To run this test:
#   1. Ensure you have a UC-enabled workspace
#   2. Authenticate to that workspace (not accounts.cloud.databricks.com):
#      databricks auth login --host https://your-workspace.cloud.databricks.com
#   3. Source environment:
#      source .env
#      export AWS_DEFAULT_REGION=us-east-1
#      export DATABRICKS_HOST="https://your-workspace.cloud.databricks.com"
#      export TF_VAR_aws_account_id="872515275153"
#   4. Uncomment the run blocks below
#   5. Run: terraform test -filter=tests/integration.tftest.hcl

provider "aws" {
  region = "us-east-1"
}

# This module requires a workspace provider with Unity Catalog enabled.
# Authentication must be workspace-level, not account-level.
provider "databricks" {
  alias = "workspace"
  # Configured via DATABRICKS_HOST + auth method (CLI, OAuth M2M, etc.)
}

variables {
  aws_partition        = "aws"
  databricks_gov_shard = null
  credential_name      = "tftest-uc-storage-cred"
  role_name            = "tftest-databricks-uc-storage-cred"
}

variable "aws_account_id" {
  type = string
}

# Uncomment to run the integration test when a UC-enabled workspace is available:

# run "setup_bucket" {
#   command = apply
#
#   variables {
#     bucket_name = "tftest-uc-storage-cred-${var.aws_account_id}"
#   }
#
#   module {
#     source = "./tests/fixtures/s3-bucket"
#   }
# }
#
# run "applies_and_produces_storage_credential" {
#   command = apply
#
#   variables {
#     aws_account_id = var.aws_account_id
#     bucket_name    = run.setup_bucket.bucket_name
#   }
#
#   assert {
#     condition     = output.storage_credential_id != ""
#     error_message = "Expected non-empty storage_credential_id after successful apply"
#   }
#
#   assert {
#     condition     = startswith(output.iam_role_arn, "arn:aws:iam::")
#     error_message = "Expected iam_role_arn to start with arn:aws:iam:: for commercial partition"
#   }
#
#   assert {
#     condition     = output.iam_role_name == "tftest-databricks-uc-storage-cred"
#     error_message = "Expected iam_role_name to match input"
#   }
#
#   assert {
#     condition     = output.external_id != ""
#     error_message = "Expected non-empty external_id generated by Databricks"
#   }
#
#   assert {
#     condition     = output.storage_credential_name == "tftest-uc-storage-cred"
#     error_message = "Expected storage_credential_name to match input"
#   }
#
#   assert {
#     condition     = output.unity_catalog_iam_arn == "arn:aws:iam::414351767826:role/unity-catalog-prod-UCMasterRole-14S5ZJVKOTYTL"
#     error_message = "Expected commercial Unity Catalog IAM ARN"
#   }
# }
